// Vendor the icon assets we use into an ES module of inline SVG strings.
//
// They have to end up *inline in the DOM* rather than as <img src>, because the
// theme toggle icons are stroked with `currentColor` — an <img> would render in
// its own document and ignore the page's theme. So the build emits a module of
// markup strings that the page injects.
//
// Sources (both installed from npm, versions pinned in package.json):
//   lucide-static  ISC        sun.svg / moon.svg   -> theme toggle
//   simple-icons   CC0-1.0    xiaohongshu.svg      -> footer link
//
// Run via `npm run vendor`.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const destDir = new URL("public/vendor/icons/", root);
// Read straight out of node_modules: both packages ship `exports` maps that
// don't expose their raw icon files or package.json to `require.resolve`.
const modules = new URL("node_modules/", root);
const read = (p) => readFile(new URL(p, modules), "utf8");
const version = async (pkg) =>
  JSON.parse(await read(`${pkg}/package.json`)).version;

const clean = (svg) =>
  svg
    // strip the lucide license comment and simple-icons' <title>
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<title>[\s\S]*?<\/title>/g, "")
    // drop intrinsic sizing so CSS controls it
    .replace(/\s(?:width|height)="[^"]*"/g, "")
    .replace(/\sclass="[^"]*"/g, "")
    .replace(/\s*\n\s*/g, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

const icons = {
  sun: clean(await read("lucide-static/icons/sun.svg")),
  moon: clean(await read("lucide-static/icons/moon.svg")),
  // simple-icons ships a bare path with no fill, so it would default to black.
  // Force currentColor and let CSS carry the brand red per theme.
  xiaohongshu: clean(await read("simple-icons/icons/xiaohongshu.svg")).replace(
    "<svg ",
    '<svg fill="currentColor" ',
  ),
};

const lucide = await version("lucide-static");
const simple = await version("simple-icons");

const body = [
  "// GENERATED by scripts/vendor-icons.mjs - do not edit.",
  `// lucide-static@${lucide} (ISC): sun, moon`,
  `// simple-icons@${simple} (CC0-1.0): xiaohongshu`,
  "",
  ...Object.entries(icons).map(([k, v]) => `export const ${k} = ${JSON.stringify(v)};`),
  "",
].join("\n");

await mkdir(fileURLToPath(destDir), { recursive: true });
await writeFile(new URL("icons.js", destDir), body, "utf8");
console.log(
  `[vendor] icons.js <- lucide-static@${lucide} (sun, moon), simple-icons@${simple} (xiaohongshu)`,
);
