#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# gen_cjk_font.py — sparse 12px bitmap CJK font for A Dark Room firmware.
#
# The glyph CLOSURE is extracted from the zh values in src/
# strings_zh.h (all 786 official translations) plus ASCII 0x20..0x7E and a
# small common-punctuation set. Every glyph is rasterized from the OFL
# Fusion Pixel 12px face (fonts/) with the SAME recipe as tools/gen_fw_fonts.py
# (fontmode="1", '0'-bottom baseline — imported from that module below), so
# the CJK glyphs share the ASCII baseline. ASCII is baked in too, so the whole
# mixed row renders through one face at one baseline (research.md §8.4, the
# recommended P1 path — no cross-font baseline drift).
#
# Output src/cjk_font12.h is a SPARSE table (research.md §8.2): the
# dense GFXfont [first,last] model would waste ~147 KB of filler over the CJK
# block, so we emit a codepoint-sorted CjkGlyph[] the firmware binary-searches.
#
# Rerun whenever strings_zh.h changes — the glyph set follows the table
# automatically (build-time closure). A round-trip proof PNG is written too.
#
# Usage:
#   gen_cjk_font.py --ttf fonts/fusion-pixel-12px-proportional-zh_hans.ttf \
#                   --strings src/strings_zh.h \
#                   --out src/cjk_font12.h [--proof proof.png]
from __future__ import annotations

import argparse
import math
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

# Reuse the ASCII-font rasterization recipe verbatim (same baseline/metrics).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_fw_fonts import build_glyph, measure_baseline  # noqa: E402

PX = 12

# Common punctuation / symbols to guarantee present regardless of the corpus
# (CJK full-width marks the translations use, plus a couple of ASCII helpers).
EXTRA = "，。、；：？！“”‘’（）《》〈〉【】—…·・～％　"


def _unescape(lit: str) -> str:
    out, i = [], 0
    while i < len(lit):
        c = lit[i]
        if c == "\\" and i + 1 < len(lit):
            n = lit[i + 1]
            out.append({"n": "\n", "r": "\r", "t": "\t",
                        '"': '"', "\\": "\\"}.get(n, n))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def zh_values(strings_h: str) -> list[str]:
    """Pull every zh value out of strings_zh.h's ADR_STRINGS[] rows."""
    text = open(strings_h, encoding="utf-8").read()
    vals = []
    # Each row: { "en_key", "zh" },  — grab both string literals, keep the 2nd.
    for m in re.finditer(r'\{\s*("(?:[^"\\]|\\.)*")\s*,\s*'
                         r'("(?:[^"\\]|\\.)*")\s*\}', text):
        vals.append(_unescape(m.group(2)[1:-1]))
    return vals


def glyph_closure(strings_h: str) -> list[int]:
    cps = set()
    for v in zh_values(strings_h):
        for ch in v:
            if ord(ch) >= 0x80:          # CJK + full-width punctuation
                cps.add(ord(ch))
    for cp in range(0x20, 0x7F):         # bake in printable ASCII
        cps.add(cp)
    for ch in EXTRA:
        cps.add(ord(ch))
    return sorted(cps)


HEADER_NOTE = """\
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Sparse 12px bitmap CJK font for A Dark Room. GENERATED by
// tools/gen_cjk_font.py from Fusion Pixel 12px (SIL OFL-1.1,
// fonts/fusion_pixel_OFL.txt) over the glyph closure of
// src/strings_zh.h + ASCII. Do not edit by hand; rerun the tool.
// Glyphs are sorted by codepoint for the binary search in cjk_text.cpp.
// Include from exactly ONE .cpp (cjk_text.cpp) — it carries the bitmap pool.
"""


def _fmt_bytes(data, per_line=16, indent="    "):
    lines = []
    for i in range(0, len(data), per_line):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append(indent + row + ",")
    return "\n".join(lines)


def emit(name, ttf, cps):
    font = ImageFont.truetype(ttf, PX)
    baseline = measure_baseline(font, PX)

    bitmaps = bytearray()
    rows = []   # (cp, off, w, h, xadv, xoff, yoff)
    for cp in cps:
        data, w, h, xadv, xoff, yoff = build_glyph(font, chr(cp), PX, baseline)
        off = len(bitmaps)
        bitmaps += data
        # int8 clamps (advance/size fit u8; offsets fit i8 for 12px glyphs).
        rows.append((cp, off, w, h, xadv, xoff, yoff))

    b = []
    b.append(HEADER_NOTE.rstrip("\n"))
    b.append(f"// {len(rows)} glyphs · {len(bitmaps)} bitmap bytes · "
             f"baseline row {baseline} · px {PX}.")
    b.append("#pragma once")
    b.append("#include <stdint.h>")
    b.append("")
    b.append("// One row per glyph, sorted by cp (ascending) for binary search.")
    b.append("// cp: Unicode codepoint (BMP). off: byte offset into the bitmap")
    b.append("// pool. w/h: ink box. xoff/yoff: ink origin vs pen baseline.")
    b.append("// adv: pen advance (proportional face).")
    b.append("struct CjkGlyph { uint16_t cp; uint16_t off; uint8_t w, h; "
             "int8_t xoff, yoff; uint8_t adv; };")
    b.append("")
    b.append(f"static const uint8_t {name}Bitmaps[] = {{")
    b.append(_fmt_bytes(bitmaps))
    b.append("};")
    b.append("")
    b.append(f"static const CjkGlyph {name}Glyphs[] = {{")
    for cp, off, w, h, xadv, xoff, yoff in rows:
        note = f"U+{cp:04X}"
        if 0x20 < cp < 0x7F:
            note += f" '{chr(cp)}'"
        elif cp >= 0x80:
            note += f" {chr(cp)}"
        b.append(f"    {{ 0x{cp:04X}, {off:5d}, {w:2d}, {h:2d}, "
                 f"{xoff:3d}, {yoff:4d}, {xadv:2d} }},   // {note}")
    b.append("};")
    b.append(f"static const uint16_t {name}Count = "
             f"sizeof({name}Glyphs) / sizeof({name}Glyphs[0]);")
    b.append(f"static const uint8_t {name}Px = {PX};")
    b.append("")
    return "\n".join(b), bitmaps, rows, baseline


def emit_proof(path, name, bitmaps, rows, baseline):
    scale = 3
    cell = PX * 2
    per = 24
    n = len(rows)
    cols = min(per, n) or 1
    rowsN = math.ceil(n / cols)
    W = cols * cell * scale + 20
    H = rowsN * cell * scale + 40
    img = Image.new("RGB", (W, H), (255, 255, 255))
    d = ImageDraw.Draw(img)
    for idx, (cp, off, w, h, xadv, xoff, yoff) in enumerate(rows):
        gc, gr = idx % cols, idx // cols
        ox = 10 + gc * cell * scale
        oy = 20 + gr * cell * scale
        base_y = oy + int(PX * scale * 1.2)
        nbits = w * h
        gb = bitmaps[off:off + (nbits + 7) // 8]
        bit = 0
        for yy in range(h):
            for xx in range(w):
                if (gb[bit >> 3] >> (7 - (bit & 7))) & 1:
                    px0 = ox + (xoff + xx) * scale
                    py0 = base_y + (yoff + yy) * scale
                    d.rectangle([px0, py0, px0 + scale - 1, py0 + scale - 1],
                                fill=(0, 0, 0))
                bit += 1
    d.text((6, H - 14), f"{name}  {len(rows)} glyphs  baseline={baseline}",
           fill=(0, 0, 0))
    img.save(path)
    return W, H


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--strings", required=True)
    ap.add_argument("--name", default="cjkFont12")
    ap.add_argument("--out", required=True)
    ap.add_argument("--proof", default=None)
    args = ap.parse_args()

    cps = glyph_closure(args.strings)
    header, bitmaps, rows, baseline = emit(args.name, args.ttf, cps)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    cjk = sum(1 for cp, *_ in rows if cp >= 0x80)
    print(f"wrote {args.out}: {len(rows)} glyphs ({cjk} CJK/punct + "
          f"{len(rows) - cjk} ASCII), {len(bitmaps)} bitmap bytes, "
          f"baseline row {baseline}")

    if args.proof:
        W, H = emit_proof(args.proof, args.name, bitmaps, rows, baseline)
        print(f"proof {args.proof} ({W}x{H})")


if __name__ == "__main__":
    main()
