#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Generate src/icons_data.h — UI glyphs rasterised from Lucide
# (https://lucide.dev, ISC License, (c) Lucide Icons and Contributors).
#
# WHY RASTERISE RATHER THAN HAND-DRAW: the first cart on the Trade bands was
# built out of fillRect/drawLine by eye and looked it (用户: "太丑了"). Lucide's
# geometry is already balanced — consistent 2px stroke, round caps and joins,
# proper optical spacing — and the panel is 1-bit-per-pixel black ink, so the
# honest way to get that geometry onto the screen is to render the real SVG at
# the real size and ship the pixels.
#
# The stroke width is scaled with the icon (Lucide draws 2px at 24px), then the
# alpha channel is thresholded: e-ink has no antialiasing to spend, and a
# half-lit pixel would just render as full black anyway.
#
# Usage (from the repo root):
#   python tools/gen_icons.py
#   python tools/gen_icons.py --preview   # also dump PNGs to /tmp for eyeballing

import argparse
import os
import re
import sys
import urllib.request

try:
    import cairosvg
    from PIL import Image
except ImportError:
    sys.exit("needs cairosvg + pillow: python -m pip install cairosvg pillow")

LUCIDE_RAW = "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/{}.svg"

# (C symbol, lucide icon name, pixel size). Size is chosen per use site.
#
# 36 for the cart: it shares the Trade band's 96px column with the "x10" label
# (36px at SCALE_BODY), and 36 + 4 + 36 = 76 leaves 10px of air each side. At 24
# it matched the text's cap height exactly and the pair read as one undifferen-
# tiated smudge — the icon is the subject here and the multiplier annotates it,
# so it should outweigh the text rather than tie with it. 36 is 1.5x Lucide's
# native 24 viewBox, an exact half-pixel scale for the 2px stroke.
ICONS = [
    ("ICON_CART", "shopping-cart", 36),
]


def fetch(name):
    with urllib.request.urlopen(LUCIDE_RAW.format(name), timeout=30) as r:
        return r.read().decode("utf-8")


def rasterise(svg, size):
    """SVG -> 1-bit rows, MSB = leftmost pixel."""
    # Lucide strokes 2 units on a 24 viewBox; cairosvg scales that with the
    # output size, which is what keeps the weight right at any size.
    png = cairosvg.svg2png(bytestring=svg.encode(), output_width=size,
                           output_height=size)
    import io
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    # Composite onto white, then threshold: ink is opaque black in the source.
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.alpha_composite(img)
    g = flat.convert("L")
    stride = (size + 7) // 8
    rows = bytearray(stride * size)
    px = g.load()
    for y in range(size):
        for x in range(size):
            if px[x, y] < 128:                 # ink
                rows[y * stride + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(rows), stride, g


def c_array(name, blob):
    out = [f"static const uint8_t {name}_BITS[{len(blob)}] = {{"]
    for off in range(0, len(blob), 12):
        out.append("    " + "".join(f"0x{b:02X}," for b in blob[off:off + 12]))
    out.append("};")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--out", default=os.path.join(root, "src", "icons_data.h"))
    ap.add_argument("--preview", action="store_true")
    args = ap.parse_args()

    parts = [HEADER_TOP]
    for sym, icon, size in ICONS:
        svg = fetch(icon)
        blob, stride, img = rasterise(svg, size)
        if args.preview:
            path = f"/tmp/{icon}_{size}.png"
            img.resize((size * 6, size * 6), Image.NEAREST).save(path)
            print(f"  preview -> {path}")
        ink = sum(bin(b).count("1") for b in blob)
        print(f"  {icon:<16} {size}x{size}  {len(blob)} bytes  {ink} ink px")
        parts.append(f"\n// lucide/{icon}, {size}x{size}, {stride} bytes/row\n"
                     f"constexpr int {sym}_W = {size};\n"
                     f"constexpr int {sym}_H = {size};\n"
                     f"constexpr int {sym}_STRIDE = {stride};\n"
                     + c_array(sym, blob) + "\n")
    with open(args.out, "w", newline="\n") as f:
        f.write("".join(parts))
    print(f"wrote {args.out} ({os.path.getsize(args.out)} bytes)")


HEADER_TOP = """\
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// UI glyphs, MACHINE GENERATED by tools/gen_icons.py — DO NOT EDIT BY HAND.
//
// Rasterised from Lucide (https://lucide.dev) at the exact size they are drawn,
// so the stroke weight, round caps and optical balance are the icon set's rather
// than something approximated with fillRect by eye.
//
//   Lucide — ISC License, Copyright (c) Lucide Icons and Contributors
//   https://github.com/lucide-icons/lucide/blob/main/LICENSE
//
// FORMAT: 1 bit per pixel, row-major, MSB = leftmost pixel, rows padded to a
// byte boundary (<SYM>_STRIDE bytes per row). A set bit is ink. Drawn by
// icons::draw() (icons.cpp), which expands a bit to the canvas's 8-bit grey.
#pragma once
#include <stdint.h>
"""

if __name__ == "__main__":
    main()
